/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/common/app-loading.vue')['default']
    IconLocalLogo: typeof import('~icons/local/logo')['default']
    IconLocalLogoFill: typeof import('~icons/local/logo-fill')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
  }
}
